version: '3'
services:
  postgres:
    image: postgis/postgis:13-master
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    volumes:
      - "./database:/var/lib/postgresql/data"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080